# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:46:39+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Path, Query

from models import (
    CreateContactInMailingList,
    CreateDistributionLinks,
    DistributionsResponse,
    EventSubscriptionsResponse,
    RetrieveDistributionLinksResponse,
    SubscribeToEventBody,
    SurveyResponse,
)

app = MCPProxy(
    description='Work with Qualtrics surveys, distributions and response events',
    title='Qualtrics API',
    version='0.2',
    servers=[{'url': 'https://fra1.qualtrics.com/API/v3'}],
)


@app.post(
    '/directories/{DirectoryId}/mailinglists/{MailingListId}/contacts',
    description=""" Creates a contact in a given mailing list """,
    tags=['mailing_list_operations'],
)
def create_contact_in_mailinglist(
    directory_id: str = Path(..., alias='DirectoryId'),
    mailing_list_id: str = Path(..., alias='MailingListId'),
    body: CreateContactInMailingList = ...,
):
    """
    Create contact in mailing list
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/distributions',
    description=""" Gets all distributions for a given survey """,
    tags=['survey_distribution_operations', 'survey_info_retrieval'],
)
def get_distributions(survey_id: str = Query(..., alias='surveyId')):
    """
    Get distributions for survey
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/distributions',
    description=""" Geneates links for individual distribution """,
    tags=['survey_distribution_operations'],
)
def generate_distribution_links(body: CreateDistributionLinks):
    """
    Generate distribution links
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/distributions/{DistributionId}/links',
    description=""" Retrieves all the individual links for a given distribution """,
    tags=['survey_distribution_operations', 'survey_info_retrieval'],
)
def retrievedistributionlinks(
    survey_id: str = Query(..., alias='surveyId'),
    distribution_id: str = Path(..., alias='DistributionId'),
):
    """
    Retrieve distribution links
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/eventsubscriptions/',
    description=""" Remove event subscription """,
    tags=['event_subscription_operations'],
)
def webhook_delete(body: SubscribeToEventBody):
    """
    Remove subscription to response event
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/eventsubscriptions/',
    description=""" Subscribe to response event """,
    tags=['event_subscription_operations'],
)
def when_a_response_is_received(body: SubscribeToEventBody):
    """
    Triggers when a response is submitted to a qualtrics survey
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/eventsubscriptions/{SubscriptionId}',
    description=""" Get event subscriptions """,
    tags=['event_subscription_operations'],
)
def get_event_subscriptions(subscription_id: str = Path(..., alias='SubscriptionId')):
    """
    Get event subscriptions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/survey-definitions/{SurveyId}',
    description=""" Gets a single Qualtrics survey speficied by its ID """,
    tags=['survey_info_retrieval'],
)
def get_survey(survey_id: str = Path(..., alias='SurveyId')):
    """
    Get survey
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
