# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:46:39+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class CreateContactInMailingList(BaseModel):
    email: Optional[str] = None
    firstName: Optional[str] = None
    lastName: Optional[str] = None
    unsubscribed: Optional[bool] = None


class CreateDistributionLinks(BaseModel):
    action: Optional[str] = 'CreateDistribution'
    description: Optional[str] = None
    expirationDate: Optional[str] = Field(None, examples=['2021-01-21 00:00:00'])
    linkType: Optional[str] = None
    mailingListId: Optional[str] = None
    surveyId: Optional[str] = None


class Meta(BaseModel):
    httpStatus: Optional[str] = None
    requestId: Optional[str] = None


class Headers(BaseModel):
    fromEmail: Optional[Any] = None
    fromName: Optional[Any] = None
    replyToEmail: Optional[Any] = None


class Message(BaseModel):
    libraryId: Optional[Any] = None
    messageId: Optional[Any] = None
    messageText: Optional[Any] = None


class Recipients(BaseModel):
    contactId: Optional[Any] = None
    libraryId: Optional[str] = None
    mailingListId: Optional[str] = None
    sampleId: Optional[Any] = None


class Stats(BaseModel):
    blocked: Optional[int] = None
    bounced: Optional[int] = None
    complaints: Optional[int] = None
    failed: Optional[int] = None
    finished: Optional[int] = None
    opened: Optional[int] = None
    sent: Optional[int] = None
    skipped: Optional[int] = None
    started: Optional[int] = None


class SurveyLink(BaseModel):
    expirationDate: Optional[str] = None
    linkType: Optional[str] = None
    surveyId: Optional[str] = None


class Element(BaseModel):
    createdDate: str
    customHeaders: Dict[str, Any]
    embeddedData: Any
    headers: Headers
    id: str
    message: Message
    modifiedDate: str
    organizationId: str
    ownerId: str
    parentDistributionId: Any
    recipients: Recipients
    requestStatus: str
    requestType: str
    sendDate: str
    stats: Stats
    surveyLink: SurveyLink


class Result(BaseModel):
    elements: Optional[List[Element]] = None
    nextPage: Optional[Any] = None


class DistributionsResponse(BaseModel):
    meta: Optional[Meta] = None
    result: Optional[Result] = None


class FieldFormdatum(BaseModel):
    key: str
    value: str


class EventSubscriptionHookSchema(BaseModel):
    field_content: str = Field(..., alias='$content')
    field_content_type: str = Field(..., alias='$content-type')
    field_formdata: Optional[List[FieldFormdatum]] = Field(None, alias='$formdata')


class Meta2(BaseModel):
    httpStatus: Optional[str] = None


class Result2(BaseModel):
    id: Optional[str] = None


class Result1(BaseModel):
    meta: Optional[Meta2] = None
    result: Optional[Result2] = None


class EventSubscriptionsResponse(BaseModel):
    meta: Optional[Meta] = None
    result: Optional[Result1] = None


class Meta3(BaseModel):
    httpStatus: Optional[str] = None
    requestId: Optional[str] = None


class Element1(BaseModel):
    contactId: str
    email: str
    exceededContactFrequency: bool
    externalDataReference: Any
    firstName: str
    lastName: str
    link: str
    linkExpiration: str
    status: str
    transactionId: Any
    unsubscribed: bool


class Result3(BaseModel):
    elements: Optional[List[Element1]] = None
    nextPage: Optional[Any] = None


class RetrieveDistributionLinksResponse(BaseModel):
    meta: Optional[Meta3] = None
    result: Optional[Result3] = None


class SubscribeToEventBody(BaseModel):
    encrypt: Optional[bool] = None
    publicationUrl: str = Field(
        ...,
        description='The internal publication URL - will be generated by PowerAutomate',
    )
    topics: str = Field(
        ...,
        description='The topics to subscribe to. Must follow the format surveyengine.completedResponse.[SurveyID]',
    )


class SurveyResponse(BaseModel):
    pass
